#伺服器設定
server:
    port: 8081

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 99988776
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate:
            ddl-auto: update
            show-sql: true
com:
    jj:
        name: J.J.Huang
        sentence: ${com.jj.name} 在這邊 ${com.jj.want}
        want: 祝大家新年快樂！